export {default as Main} from './Main'
export {default as Register} from './Register'
export {default as Home} from './Home'
export {default as Profil} from './Profil'
export {default as User} from './User'